# Single nginx-version for all stages
FROM nginx:1.21 AS nginx_version

# Prepare nginx-configurations
FROM nginx_version AS build

WORKDIR /etc/nginx
# Delete default config, will be replaced at startup from the template-file
RUN rm nginx.conf
# Copy static config-parts
COPY forward_to_flask.conf ssl.conf ./

# Prepare "envsubst" of environment variable "APP_ENV" in "main_nginx.conf.template"-file
COPY main_nginx.conf.template templates/nginx.conf.template
COPY prod_ssl.conf.template templates/server.conf.template
# Link filled templates back to their needed position
RUN mkdir filled_templates && ln -s /etc/nginx/filled_templates/nginx.conf /etc/nginx/nginx.conf
RUN mkdir prod && ln -s /etc/nginx/filled_templates/server.conf /etc/nginx/prod/server.conf

# Copy dynamic configuration-files in folders that are named after active environment (dev, prod, test)
# Used afterwards in template replacement inside nginx-config files
ADD local_no_ssl.conf dev/server.conf
ADD local_no_ssl.conf test/server.conf

# Copy configurations on top of clean base-image
FROM nginx_version

ENV NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/filled_templates
COPY --from=build /etc/nginx /etc/nginx