FROM python:3.9-slim-bullseye AS build

WORKDIR /home/flandria_user/flandria

# Setup virtual environment
RUN python -m venv venv
ENV PATH="/home/flandria_user/flandria/venv/bin:$PATH"

# Install requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy only needed files from local repository
COPY app.py run_stack/wsgi.py ./
COPY migrations migrations
COPY database_updater database_updater
COPY webapp webapp

FROM python:3.9-alpine

# Add new user for flandria-server
RUN adduser flandria_user --disabled-password --home /home/flandria_user
WORKDIR /home/flandria_user/flandria

# Copy only needed files from build-stage (including venv as a subfolder)
COPY --from=build --chown=flandria_user /home/flandria_user/flandria .

# Active virtual environment
ENV PATH="/home/flandria_user/flandria/venv/bin:$PATH"

# Start webserver
# Replace Flask internal server with Gunicorn (application server) for productional usage
# See: https://www.toptal.com/flask/flask-production-recipes
USER flandria_user
EXPOSE 5000
CMD gunicorn --workers 8 --bind 0.0.0.0:5000 wsgi:app --max-requests 10000 --timeout 5 --keep-alive 5 --log-level info