FROM python:3.9-slim-bullseye

# Add new user for flandria-server
RUN useradd -ms /bin/bash flandria_user && chown flandria_user /home/flandria_user
WORKDIR /home/flandria_user/flandria

# Install requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy only needed files from build-stage or local repository
COPY --from=build --chown=flandria_user /home/flandria_user/flandria/webapp webapp
COPY --chown=flandria_user app.py run_stack/wsgi.py ./
ADD --chown=flandria_user database_updater database_updater
ADD --chown=flandria_user migrations migrations

# Start webserver
# Replace Flask internal server with Gunicorn (application server) for productional usage
# See: https://www.toptal.com/flask/flask-production-recipes
USER flandria_user
EXPOSE 5000
CMD gunicorn --workers 8 --bind 0.0.0.0:5000 wsgi:app --max-requests 10000 --timeout 5 --keep-alive 5 --log-level info